€name: Post ReviewBoard review
description: Post a review to a ReviewBoard server
author: SMillerDev
branding:
  icon: mail
  color: yellow
inputs:
  token:
    description: Token to be used for ReviewBoard authentication
    required: true
  url:
    description: ReviewBoard URL
    required: false
    default: 'https://demo.reviewboard.org/'
  review_id:
    description: ReviewBoard review ID
    required: false
    default: ''
  draft:
    description: Post the review as draft
    required: false
    default: false
  header:
    description: Review header
    required: false
    default: ''
  footer:
    description: Review footer
    required: false
    default: ''
runs:
  using: composite
  steps:
    - shell: bash
      id: set-review-header
      run: echo "${{ inputs.header }}" > $GITHUB_ACTION_PATH/review_header.tmp.md

    - shell: bash
      id: set-review-footer
      run: echo "${{ inputs.footer }}" > $GITHUB_ACTION_PATH/review_footer.tmp.md

    - shell: bash
      id: post-review
      env:
        IS_PUBLIC: "${{ !inputs.draft }}"
        REVIEW_ID: "${{ inputs.review_id }}"
        REVIEWBOARD_URL: "${{ inputs.url }}"
        REVIEWBOARD_API_TOKEN: "${{ inputs.token }}"
      run: "$GITHUB_ACTION_PATH/main.sh" $REVIEW_ID $IS_PUBLIC
